name       : usbmuxd
version    : 1.1.1
release    : 7
source     :
    - git|https://github.com/libimobiledevice/usbmuxd.git : 02f39959800e95f1b83128fd09751ad18a7488cc
license    : GPL-3.0-or-later
component  : system.utils
summary    : A socket daemon to multiplex connections from and to iOS devices.
description: |
    A socket daemon to multiplex connections from and to iOS devices.
builddeps  :
    - pkgconfig(libimobiledevice-1.0)
    - pkgconfig(libusb-1.0)
setup      : |
    %reconfigure --prefix=/usr --sbindir=/usr/bin
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/usbmux.sysusers $installdir/%libdir%/sysusers.d/usbmux.conf
