name       : usbmuxd
version    : 1.1.0
release    : 3
source     :
    - http://www.libimobiledevice.org/downloads/usbmuxd-1.1.0.tar.bz2 : 3e8948b4fe4250ee5c4bd41ccd1b83c09b8a6f5518a7d131a66fd38bd461b42d
license    : GPL-3
summary    : A socket daemon to multiplex connections from and to iOS devices.
description: |
    A socket daemon to multiplex connections from and to iOS devices.
builddeps  :
    - pkgconfig(libimobiledevice-1.0)
    - pkgconfig(libplist)
    - pkgconfig(libusb-1.0)
    - libusbmuxd
setup      : |
    %configure --prefix=/usr --sbindir=/usr/bin
    %make
install    : |
    mkdir -p %installroot%/etc
    %make_install
    mv %installroot%/usr/lib/systemd %installroot%/etc/
    mv %installroot%/usr/lib/udev %installroot%/etc/
    rmdir %installroot%/usr/lib
