name       : usbmuxd
version    : 1.1.0
release    : 5
source     :
    - https://github.com/libimobiledevice/usbmuxd/archive/1.1.0.tar.gz : 6d33a9a60bfb729e060950f650495ee89f8265970f851a77b77aec3bab4c1066
license    : GPL-3.0-or-later
component  : system.utils
summary    : A socket daemon to multiplex connections from and to iOS devices.
description: |
    A socket daemon to multiplex connections from and to iOS devices.
builddeps  :
    - pkgconfig(libimobiledevice-1.0)
    - pkgconfig(libplist)
    - pkgconfig(libusb-1.0)
    - libusbmuxd
setup      : |
    %reconfigure --prefix=/usr --sbindir=/usr/bin
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/usbmux.sysusers $installdir/%libdir%/sysusers.d/usbmux.conf
